name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List project files (Debugging Step)
        run: ls -la

      - name: Change directory to backend
        run: cd backend

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./

      - name: Run tests
        run: npm test
        working-directory: ./

      - name: Build project
        run: npm run build
        working-directory: ./

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production
        run: echo "Deploying application..."
